Repository falcosecurity/evolution, pull requests merged in 2020-05, with the labels that each got.

#17 new(examples): move examples from falco repo to here
  README.md
  examples/OWNERS
  examples/bad-mount-cryptomining/README.md
  examples/bad-mount-cryptomining/attacker-nginx.conf
  examples/bad-mount-cryptomining/attacker_files/config_1.json
  examples/bad-mount-cryptomining/attacker_files/logo3.jpg
  examples/bad-mount-cryptomining/attacker_files/minerd
  examples/bad-mount-cryptomining/demo.yml
  examples/bad-mount-cryptomining/docker123321-mysql-container.json
  examples/bad-mount-cryptomining/host-machine/Dockerfile
  examples/bad-mount-cryptomining/host-machine/start-cron-and-dind.sh
  examples/bad-mount-cryptomining/launch_malicious_container.sh
  examples/k8s_audit_config/README.md
  examples/k8s_audit_config/apiserver-config.patch.sh
  examples/k8s_audit_config/audit-policy.yaml
  examples/k8s_audit_config/audit-sink.yaml.in
  examples/k8s_audit_config/enable-k8s-audit.sh
  examples/k8s_audit_config/webhook-config.yaml.in
  examples/mitm-sh-installer/README.md
  examples/mitm-sh-installer/botnet_master.sh
  examples/mitm-sh-installer/demo.yml
  examples/mitm-sh-installer/evil_web_root/botnet_client.py
  examples/mitm-sh-installer/fbash
  examples/mitm-sh-installer/nginx.conf
  examples/mitm-sh-installer/web_root/install-software.sh
  examples/nodejs-bad-rest-api/README.md
  examples/nodejs-bad-rest-api/demo.yml
  examples/nodejs-bad-rest-api/package.json
  examples/nodejs-bad-rest-api/run
  examples/nodejs-bad-rest-api/server.js
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XXL

#21 Restyle the Kubernetes manifests structure
  deploy/kubernetes/k8s-only-audit/README.md
  deploy/kubernetes/k8s-only-audit/deployment.yaml
  deploy/kubernetes/k8s-only-audit/falco.yaml
  deploy/kubernetes/k8s-only-audit/rbac.yaml
  deploy/kubernetes/k8s-only-audit/rules/k8s_audit_rules.yaml
  deploy/kubernetes/k8s-only-audit/service.yaml
  deploy/kubernetes/kernel-and-k8s-audit/README.md
  deploy/kubernetes/kernel-and-k8s-audit/daemonset-least-privilege.yaml
  deploy/kubernetes/kernel-and-k8s-audit/daemonset.yaml
  deploy/kubernetes/kernel-and-k8s-audit/falco.yaml
  deploy/kubernetes/kernel-and-k8s-audit/rbac.yaml
  deploy/kubernetes/kernel-and-k8s-audit/rules/falco_rules.local.yaml
  deploy/kubernetes/kernel-and-k8s-audit/rules/falco_rules.yaml
  deploy/kubernetes/kernel-and-k8s-audit/rules/k8s_audit_rules.yaml
  deploy/kubernetes/kernel-and-k8s-audit/service.yaml
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/M

#23 docs(README.md): add `/deploy`
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#28 revert: "docs(.github): remove files inherited from the org"
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/L
