Repository falcosecurity/evolution, pull requests merged in 2021-08, with the labels that each got.

#95 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco/templates/clusterrole.yaml
  deploy/kubernetes/falco/templates/clusterrolebinding.yaml
  deploy/kubernetes/falco/templates/configmap.yaml
  deploy/kubernetes/falco/templates/daemonset.yaml
  deploy/kubernetes/falco/templates/serviceaccount.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/S

#88 projects census
  README.md
Labels: kind/documentation, kind/cleanup, dco-signoff: yes, lgtm, approved, size/M

#96 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falcosidekick/templates/deployment.yaml
  deploy/kubernetes/falcosidekick/templates/rbac.yaml
  deploy/kubernetes/falcosidekick/templates/secrets.yaml
  deploy/kubernetes/falcosidekick/templates/service.yaml
Labels: dco-signoff: yes, lgtm, approved, needs-kind, size/M

#97 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falcosidekick/templates/deployment.yaml
  deploy/kubernetes/falcosidekick/templates/rbac.yaml
  deploy/kubernetes/falcosidekick/templates/secrets.yaml
  deploy/kubernetes/falcosidekick/templates/service.yaml
Labels: dco-signoff: yes, lgtm, approved, needs-kind, size/S

#98 docs: add falcosecurity/katacoda-scenarios to the projects list
  README.md
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS, kind/incubating
