Repository falcosecurity/evolution, pull requests merged in 2021-03, with the labels that each got.

#50 docs(integrations): clean up archived project
  integrations/kubernetes-response-engine/README.md
Labels: approved, dco-signoff: yes, kind/cleanup, kind/documentation, lgtm, size/XS

#52 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco/templates/clusterrole.yaml
  deploy/kubernetes/falco/templates/clusterrolebinding.yaml
  deploy/kubernetes/falco/templates/configmap.yaml
  deploy/kubernetes/falco/templates/daemonset.yaml
  deploy/kubernetes/falco/templates/serviceaccount.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/XXL

#53 Add initial support for Kustomizations
  deploy/kubernetes/falco/kustomization.yaml
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XS

#54 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falcosidekick/templates/deployment.yaml
  deploy/kubernetes/falcosidekick/templates/rbac.yaml
  deploy/kubernetes/falcosidekick/templates/secrets.yaml
  deploy/kubernetes/falcosidekick/templates/service.yaml
  deploy/kubernetes/falcosidekick/templates/tests/test-connection.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/XL
