Repository falcosecurity/evolution, pull requests merged in 2021-04, with the labels that each got.

#55 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco-exporter/templates/daemonset.yaml
  deploy/kubernetes/falco-exporter/templates/service.yaml
  deploy/kubernetes/falco-exporter/templates/serviceaccount.yaml
  deploy/kubernetes/falco-exporter/templates/tests/test-connection.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/L

#57 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco-exporter/kustomization.yaml
  deploy/kubernetes/falco-exporter/templates/daemonset.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/XS

#58 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falcosidekick/kustomization.yaml
  deploy/kubernetes/falcosidekick/templates/deployment.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/XS

#60 chore(usage-metrics/distribution-logs): change go mod definitions
  usage-metrics/distribution-logs/go.mod
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#61 docs: evolution gif
  README.md
  img/pidgeotto.gif
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#63 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falcosidekick/templates/deployment.yaml
  deploy/kubernetes/falcosidekick/templates/rbac.yaml
  deploy/kubernetes/falcosidekick/templates/secrets.yaml
  deploy/kubernetes/falcosidekick/templates/service.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/M

#64 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco/kustomization.yaml
  deploy/kubernetes/falco/templates/clusterrole.yaml
  deploy/kubernetes/falco/templates/clusterrolebinding.yaml
  deploy/kubernetes/falco/templates/configmap.yaml
  deploy/kubernetes/falco/templates/daemonset.yaml
  deploy/kubernetes/falco/templates/serviceaccount.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/XXL

#65 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco/templates/clusterrole.yaml
  deploy/kubernetes/falco/templates/clusterrolebinding.yaml
  deploy/kubernetes/falco/templates/configmap.yaml
  deploy/kubernetes/falco/templates/daemonset.yaml
  deploy/kubernetes/falco/templates/serviceaccount.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/S

#66 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falcosidekick/templates/deployment.yaml
  deploy/kubernetes/falcosidekick/templates/rbac.yaml
  deploy/kubernetes/falcosidekick/templates/secrets.yaml
  deploy/kubernetes/falcosidekick/templates/service.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/S

#68 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco/templates/clusterrole.yaml
  deploy/kubernetes/falco/templates/clusterrolebinding.yaml
  deploy/kubernetes/falco/templates/configmap.yaml
  deploy/kubernetes/falco/templates/daemonset.yaml
  deploy/kubernetes/falco/templates/serviceaccount.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/S
