Repository falcosecurity/evolution, pull requests merged in 2021-06, with the labels that each got.

#75 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco/templates/clusterrole.yaml
  deploy/kubernetes/falco/templates/clusterrolebinding.yaml
  deploy/kubernetes/falco/templates/configmap.yaml
  deploy/kubernetes/falco/templates/daemonset.yaml
  deploy/kubernetes/falco/templates/serviceaccount.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/S

#76 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco/templates/clusterrole.yaml
  deploy/kubernetes/falco/templates/clusterrolebinding.yaml
  deploy/kubernetes/falco/templates/configmap.yaml
  deploy/kubernetes/falco/templates/daemonset.yaml
  deploy/kubernetes/falco/templates/serviceaccount.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/S

#74 Configure auditing for falco on OpenShift 4.x
  examples/k8s_audit_config/README.md
  examples/k8s_audit_config/machine-config.yaml.in
Labels: approved, area/examples, area/integrations, dco-signoff: yes, kind/documentation, lgtm, size/M

#77 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco/templates/clusterrole.yaml
  deploy/kubernetes/falco/templates/clusterrolebinding.yaml
  deploy/kubernetes/falco/templates/configmap.yaml
  deploy/kubernetes/falco/templates/daemonset.yaml
  deploy/kubernetes/falco/templates/serviceaccount.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/S

#78 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco/templates/clusterrole.yaml
  deploy/kubernetes/falco/templates/clusterrolebinding.yaml
  deploy/kubernetes/falco/templates/configmap.yaml
  deploy/kubernetes/falco/templates/daemonset.yaml
  deploy/kubernetes/falco/templates/serviceaccount.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/S

#80 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco/templates/clusterrole.yaml
  deploy/kubernetes/falco/templates/clusterrolebinding.yaml
  deploy/kubernetes/falco/templates/configmap.yaml
  deploy/kubernetes/falco/templates/daemonset.yaml
  deploy/kubernetes/falco/templates/serviceaccount.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/S

#81 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falcosidekick/templates/deployment.yaml
  deploy/kubernetes/falcosidekick/templates/rbac.yaml
  deploy/kubernetes/falcosidekick/templates/secrets.yaml
  deploy/kubernetes/falcosidekick/templates/service.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/M

#82 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco/templates/clusterrole.yaml
  deploy/kubernetes/falco/templates/clusterrolebinding.yaml
  deploy/kubernetes/falco/templates/configmap.yaml
  deploy/kubernetes/falco/templates/daemonset.yaml
  deploy/kubernetes/falco/templates/serviceaccount.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/S

#83 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco/templates/clusterrole.yaml
  deploy/kubernetes/falco/templates/clusterrolebinding.yaml
  deploy/kubernetes/falco/templates/configmap.yaml
  deploy/kubernetes/falco/templates/daemonset.yaml
  deploy/kubernetes/falco/templates/serviceaccount.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/S

#84 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falcosidekick/templates/deployment.yaml
  deploy/kubernetes/falcosidekick/templates/rbac.yaml
  deploy/kubernetes/falcosidekick/templates/secrets.yaml
  deploy/kubernetes/falcosidekick/templates/service.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/S
