Repository falcosecurity/evolution, pull requests merged in 2022-02, with the labels that each got.

#124 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco/templates/clusterrole.yaml
  deploy/kubernetes/falco/templates/clusterrolebinding.yaml
  deploy/kubernetes/falco/templates/configmap.yaml
  deploy/kubernetes/falco/templates/daemonset.yaml
  deploy/kubernetes/falco/templates/serviceaccount.yaml
Labels: dco-signoff: yes, size/XXL, lgtm, approved, needs-kind

#125 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco-exporter/templates/daemonset.yaml
  deploy/kubernetes/falco-exporter/templates/service.yaml
  deploy/kubernetes/falco-exporter/templates/serviceaccount.yaml
Labels: dco-signoff: yes, lgtm, approved, needs-kind, size/S

#126 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco/templates/clusterrole.yaml
  deploy/kubernetes/falco/templates/clusterrolebinding.yaml
  deploy/kubernetes/falco/templates/configmap.yaml
  deploy/kubernetes/falco/templates/daemonset.yaml
  deploy/kubernetes/falco/templates/serviceaccount.yaml
Labels: dco-signoff: yes, lgtm, approved, needs-kind, size/S

#128 deps(integrations/anchore-falco): update dependencies
  integrations/anchore-falco/Pipfile.lock
Labels: kind/cleanup, dco-signoff: yes, lgtm, approved, size/L, area/integrations

#129 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco/templates/clusterrole.yaml
  deploy/kubernetes/falco/templates/clusterrolebinding.yaml
  deploy/kubernetes/falco/templates/configmap.yaml
  deploy/kubernetes/falco/templates/daemonset.yaml
  deploy/kubernetes/falco/templates/serviceaccount.yaml
Labels: dco-signoff: yes, lgtm, approved, needs-kind, size/S
