Repository falcosecurity/evolution, pull requests merged in 2022-11, with the labels that each got.

#210 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#212 update(README): add syscalls bumper to incubating projects.
  README.md
Labels: dco-signoff: yes, lgtm, approved, size/XS, kind/incubating

#211 update: maintainers list and evolution resources
  MAINTAINERS.md
  README.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S

#214 new(people): add Logan Bond.
  people/affiliations.json
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#215 vote: update(docs): GOVERNANCE.md
  GOVERNANCE.md
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS, area/governance

#217 fix(repositories): add syscalls-bumper.
  repositories.yaml
Labels: kind/bug, dco-signoff: yes, lgtm, approved, size/XS

#213 update: maintainers list and evolution resources
  MAINTAINERS.md
  README.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#218 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#220 fix: correct exoner4ted affiliation
  MAINTAINERS.md
  maintainers.yaml
  people/affiliations.json
Labels: kind/documentation, kind/cleanup, dco-signoff: yes, lgtm, approved, size/XS
