Repository falcosecurity/evolution, pull requests merged in 2022-06, with the labels that each got.

#147 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco/templates/clusterrole.yaml
  deploy/kubernetes/falco/templates/clusterrolebinding.yaml
  deploy/kubernetes/falco/templates/configmap.yaml
  deploy/kubernetes/falco/templates/daemonset.yaml
  deploy/kubernetes/falco/templates/serviceaccount.yaml
Labels: dco-signoff: yes, lgtm, approved, needs-kind, size/S

#148 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falcosidekick/templates/deployment.yaml
  deploy/kubernetes/falcosidekick/templates/rbac-ui.yaml
  deploy/kubernetes/falcosidekick/templates/rbac.yaml
  deploy/kubernetes/falcosidekick/templates/secrets.yaml
  deploy/kubernetes/falcosidekick/templates/service.yaml
Labels: dco-signoff: yes, lgtm, approved, needs-kind, size/S

#149 chore(deploy): cleanup folder and add notice
  deploy/README.md
  deploy/kind/README.md
  deploy/kind/audit.yaml
  deploy/kubeadm/README.md
  deploy/kubeadm/audit.yaml
  deploy/kubernetes/README.md
  deploy/kubernetes/falco-exporter/kustomization.yaml
  deploy/kubernetes/falco-exporter/templates/daemonset.yaml
  deploy/kubernetes/falco-exporter/templates/service.yaml
  deploy/kubernetes/falco-exporter/templates/serviceaccount.yaml
  deploy/kubernetes/falco-exporter/templates/tests/test-connection.yaml
  deploy/kubernetes/falco-k8s-audit-sink/audit-sink.yaml.in
  deploy/kubernetes/falco-k8s-audit-sink/service.yaml
  deploy/kubernetes/falco/kustomization.yaml
  deploy/kubernetes/falco/templates/clusterrole.yaml
  deploy/kubernetes/falco/templates/clusterrolebinding.yaml
  deploy/kubernetes/falco/templates/configmap.yaml
  deploy/kubernetes/falco/templates/daemonset.yaml
  deploy/kubernetes/falco/templates/serviceaccount.yaml
  deploy/kubernetes/falcosidekick/kustomization.yaml
  deploy/kubernetes/falcosidekick/templates/deployment.yaml
  deploy/kubernetes/falcosidekick/templates/rbac-ui.yaml
  deploy/kubernetes/falcosidekick/templates/rbac.yaml
  deploy/kubernetes/falcosidekick/templates/secrets.yaml
  deploy/kubernetes/falcosidekick/templates/service.yaml
  deploy/kubernetes/falcosidekick/templates/tests/test-connection.yaml
Labels: kind/documentation, kind/cleanup, dco-signoff: yes, size/XXL, lgtm, approved, area/deploy

#150 docs: promote de-facto official projects
  README.md
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS, kind/officialsupport
