Repository falcosecurity/evolution, pull requests merged in 2022-09, with the labels that each got.

#183 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#184 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#185 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#186 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#187 docs(REAMDE.md): correct link to security policy
  README.md
Labels: kind/bug, kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#188 chore(repositories.yaml): add missing descriptions
  repositories.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#189 update: maintainers list and evolution resources
  MAINTAINERS.md
  README.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S

#192 update(README): fix typo
  README.md
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#194 docs(MAINTAINERS_GUIDELINES.md): linking core maintainers duties
  MAINTAINERS_GUIDELINES.md
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#190 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#196 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#199 update(MAINTAINERS_GUIDELINES.md): additional (on|off)boarding steps for core maintainers
  MAINTAINERS_GUIDELINES.md
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S

#197 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#200 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#202 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#201 update(repositories.yaml): fix typo leftover
  repositories.yaml
Labels: kind/documentation, kind/cleanup, dco-signoff: yes, lgtm, approved, size/XS

#203 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#205 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#206 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS
