Repository falcosecurity/evolution, pull requests merged in 2022-01, with the labels that each got.

#119 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco-exporter/templates/daemonset.yaml
  deploy/kubernetes/falco-exporter/templates/service.yaml
  deploy/kubernetes/falco-exporter/templates/serviceaccount.yaml
Labels: dco-signoff: yes, lgtm, approved, needs-kind, size/XS

#120 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco-exporter/templates/daemonset.yaml
  deploy/kubernetes/falco-exporter/templates/service.yaml
  deploy/kubernetes/falco-exporter/templates/serviceaccount.yaml
Labels: dco-signoff: yes, lgtm, approved, needs-kind, size/XS

#122 Add falcosecurity/plugin-sdk-go as an incubating project
  README.md
Labels: dco-signoff: yes, lgtm, approved, size/XS, kind/incubating, area/integrations

#123 update(deploy/kubernetes): Falco deployment files
  deploy/kubernetes/falco/templates/clusterrole.yaml
  deploy/kubernetes/falco/templates/clusterrolebinding.yaml
  deploy/kubernetes/falco/templates/configmap.yaml
  deploy/kubernetes/falco/templates/daemonset.yaml
  deploy/kubernetes/falco/templates/serviceaccount.yaml
Labels: dco-signoff: yes, lgtm, approved, needs-kind, size/S
