Repository falcosecurity/evolution, pull requests merged in 2023-10, with the labels that each got.

#321 update: maintainers list and evolution resources
  MAINTAINERS.md
  README.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#325 (chore) Switch dwindsor's affiliation to Independent
  people/affiliations.json
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#323 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#328 update(affiliations): add therealbobo to maintainers list
  people/affiliations.json
Labels: dco-signoff: yes, lgtm, approved, needs-kind, size/XS, area/governance

#326 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S

#327 docs: add spdx identifier
  Makefile
  utils/Makefile
  utils/cmd/maintainers.go
  utils/cmd/readme.go
  utils/cmd/utils.go
  utils/pkg/utils/text.go
  utils/pkg/utils/types.go
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S, area/utils

#331 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#332 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#333 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS
