Repository falcosecurity/evolution, pull requests merged in 2023-07, with the labels that each got.

#280 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#283 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S

#287 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#286 sign off commit
  people/affiliations.json
Labels: dco-signoff: yes, lgtm, approved, needs-kind, size/XS

#288 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#289 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#290 new(repositories): add kernel-testing
  repositories.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS, kind/incubating, area/utils

#291 update: maintainers list and evolution resources
  MAINTAINERS.md
  README.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S

#292 update(persons): add Aldo Lacuku
  people/affiliations.json
Labels: dco-signoff: yes, lgtm, approved, needs-kind, size/XS

#293 fix(people/affiliations.json): correct typos and cases
  people/affiliations.json
Labels: kind/bug, kind/documentation, kind/cleanup, dco-signoff: yes, lgtm, approved, size/XS

#294 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/M

#295 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#296 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS
