Repository falcosecurity/evolution, pull requests merged in 2024-07, with the labels that each got.

#392 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S

#393 chore: add sgaist to affiliations
  people/affiliations.json
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS, area/utils

#394 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S

#395 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#396 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS
