Repository falcosecurity/evolution, pull requests merged in 2024-06, with the labels that each got.

#387 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S

#388 update(people/affiliations.json): add loresuso to affiliations
  people/affiliations.json
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS, area/governance

#389 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S

#390 docs(people): update affiliations.json
  people/affiliations.json
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#391 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S
