Repository falcosecurity/evolution, pull requests merged in 2024-11, with the labels that each got.

#411 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#413 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#414 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#416 people/affiliations.json
  people/affiliations.json
Labels: dco-signoff: yes, lgtm, approved, needs-kind, size/XS

#417 update(repositories.yaml): add falco-actions
  repositories.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS, kind/sandbox

#415 update: maintainers list and evolution resources
  MAINTAINERS.md
  README.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S
