Repository falcosecurity/evolution, pull requests merged in 2024-03, with the labels that each got.

#368 chore: update maxgio92 affiliation
  MAINTAINERS.md
  maintainers.yaml
  people/affiliations.json
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#367 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#369 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#370 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#372 add affiliation
  people/affiliations.json
Labels: dco-signoff: yes, lgtm, approved, needs-kind, size/XS

#371 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S
