Repository falcosecurity/evolution, pull requests merged in 2024-05, with the labels that each got.

#382 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#380 fix: change wording to "stable"
  .github/ISSUE_TEMPLATE/repo_promoting_to_stable.md
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#383 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S

#384 update: maintainers list and evolution resources
  people/affiliations.json
Labels: dco-signoff: yes, lgtm, approved, needs-kind, size/XS

#385 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S
