Repository falcosecurity/evolution, pull requests merged in 2025-05, with the labels that each got.

#448 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S

#450 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S

#452 update: change affiliation
  people/affiliations.json
Labels: kind/cleanup, dco-signoff: yes, lgtm, approved, size/XS, area/governance

#453 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S

#454 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#455 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS
