Repository falcosecurity/evolution, pull requests merged in 2025-01, with the labels that each got.

#426 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#427 update(repositories.yaml): add elftoolchain
  repositories.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS, kind/stable, area/proposals

#428 update: maintainers list and evolution resources
  MAINTAINERS.md
  README.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S

#429 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#430 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#431 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS

#434 update: maintainers list and evolution resources
  MAINTAINERS.md
  README.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S

#436 Add scraly in affiliations.json
  people/affiliations.json
Labels: dco-signoff: yes, lgtm, approved, needs-kind, size/XS

#435 Update affiliations.json
  people/affiliations.json
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/S

#438 update(affiliations.json): Include Nedim Sabic in affiliations.json
  people/affiliations.json
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS, area/utils

#437 update: maintainers list and evolution resources
  MAINTAINERS.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/M

#433 update(repositories.yaml): promote plugin-sdk-cpp to incubating
  repositories.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS, kind/incubating

#439 update: maintainers list and evolution resources
  MAINTAINERS.md
  README.md
  maintainers.yaml
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS
